imports:
    - { resource: ../config.d/ }

framework:
    profiler:
        only_exceptions: false
    router:
        resource: '%kernel.config_dir%/routing/routing_dev.yml'
        strict_requirements: true
    templating:
        engines: [twig]

monolog:
    handlers:
        buffer:
            channels: [!event]
            handler: easylog
            type: buffer
        console:
            channels: [!event, !doctrine]
        easylog:
            id: easycorp.easylog.handler
            type: service

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

web_profiler:
    toolbar: true
    intercept_redirects: false

services:
    easycorp.easylog.handler:
        class: EasyCorp\EasyLog\EasyLogHandler
        arguments:
            - '%kernel.logs_dir%/%kernel.environment%.easylog.log'
        public: false
